MakerStore/MakerStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MakerStore.Models;
using MakerStore.ViewModels;

namespace MakerStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        MakerStoreEntities storeDB = new MakerStoreEntities();

        //
        // GET: /ShoppingCart/

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };


            return View(viewModel);
        }

        //
        // GET: /ShoppingCart/AddtoCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedAlbum = storeDB.Products.Single(product => product.ProductID == id);

            // Ad it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        //AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.Carts.Single(item => item.ProductID == id).Product.Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) + " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                DeleteId = id
            };

            return Json(results);
        }

        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }
    }
}

MakerStore/MakerStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MakerStore.Models;

namespace MakerStore.Controllers
{
    public class StoreController : Controller
    {
        MakerStoreEntities storeDB = new MakerStoreEntities();

        //
        // GET: /Store/

        public ActionResult Index()
        {
            var categories = storeDB.Categories.ToList();

            return View(categories);
        }

        //
        // GET: /Store/Browse?category=robotics

        public ActionResult Browse(string category)
        {
            // Retrieve Category and its Associated Products from database
            var categoryModel = storeDB.Categories.Include("Products").Single(c => c.Name == category);

            return View(categoryModel);
        }

        //
        // GET: /Store/Details/5

        public ActionResult Details(int id)
        {
            var product = storeDB.Products.Find(id);
            return View(product);
        }

        //
        // GET: /Store/CategoryMenu

        [ChildActionOnly]
        public ActionResult CategoryMenu()
        {
            var categories = storeDB.Categories.ToList();

            return PartialView(categories);
        }

    }
}

MakerStore/MakerStore/Views/Store/Browse.cshtml
@model MakerStore.Models.Category

@{
    ViewBag.Title = "Browse Albums";
}

<div class="genre">
    <h3><em>@Model.Name</em> Products</h3>

    <ul id="album-list">
        @foreach (var product in Model.Products)
        {
            <li>
                <a href="@Url.Action("Details", new { id = product.ProductID})">
                    <img alt="@product.Name" src="@product.PictureURL" />
                    <span>@product.Name</span>
                </a>
            </li>
        }
    </ul>
</div>

MakerStore/MakerStore/Views/Store/CategoryMenu.cshtml
@model IEnumerable<MakerStore.Models.Category>

<ul id="categories">
    @foreach (var category in Model)
    {
        <li>@Html.ActionLink(category.Name, "Browse", "Store", new { Category = category.Name }, null)</li>
    }
</ul>

MakerStore/MakerStore/Views/Store/Details.cshtml
@model MakerStore.Models.Product

@{
    ViewBag.Title = "Product - " + Model.Name;
}

<h2>Product: @Model.Name</h2>

<p>
    <img alt="@Model.Name" src="@Model.PictureURL" />
</p>

<div id="product-details">
    <p>
        <em>Category:</em>
        @Model.Category.Name
    </p>
    <p>
        <em>User:</em>
        @Model.User.UserName
    </p>
    <p>
        <em>Price:</em>
        @String.Format("{0:F}", Model.Price)
    </p>
    <p class="button">
        @Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new { id = Model.ProductID }, null)
    </p>
</div>

MakerStore/MakerStore/Views/Store/Index.cshtml
@model IEnumerable<MakerStore.Models.Category>

@{
    ViewBag.Title = "Store";
}

<h3>Browse Categories</h3>

<p>Select from @Model.Count() categories:</p>
<ul>
    @foreach (var category in Model)
    {
        <li>@Html.ActionLink(category.Name, "Browse", new { category = category.Name })</li>
    }
</ul>